all:
	g++ -std=c++11 -O2 Pineapple_Cakes_In_the_Plate2.cpp -o Pineapple_Cakes_In_the_Plate2.out
exe:
	./Pineapple_Cakes_In_the_Plate2.out <input.txt
clean:
	rm -rf Pineapple_Cakes_In_the_Plate2.out